### ISSUE TITLE
Layout misplaced.

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/YTVideoOverlay#4]
To reproduce:

1. Launch YT app

2. Watch any Shorts, either Shorts in Home feeds or Shorts in Shorts tab is fine.

3. Leave the Shorts, back to Home feeds.

4. Click and watch any video in Home feeds.

5. The buttons of YouMute and YouQuality are misplaced.

Tested on YouTube 18.34.5 and 18.35.4.

Environment:
iPhone 11 Pro Max
iOS 14.8
unc0ver 8.0.2

Images:
![image](https://github.com/PoomSmart/YTVideoOverlay/assets/15531137/4922ee51-2bdb-449f-9a41-1495b32d8b76)

![image](https://github.com/PoomSmart/YTVideoOverlay/assets/15531137/7bb15d78-22ba-46e1-92c7-d08cf0858038)

**Comment by PoomSmart** [comment]
Fixed in 1.1.1

**Comment by CySxL** [comment]
Thanks ❤️
