### ISSUE TITLE
Crash in Shorts

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/YTVideoOverlay#5]
YTVideoOverlay crashes YouTube after playings some Shorts.

Tested with YouTube 18.38.2/YTVideoOverlay 1.1.1

Crash Logs: https://pastebin.com/QsjeCAXk

Screenshot: ![image](https://github.com/PoomSmart/YTVideoOverlay/assets/15531137/32070e09-f0d0-4f00-b0a2-00a8b13c31ca)

**Comment by CySxL** [comment]
Same thing happens on YT 18.43.4
![image](https://github.com/PoomSmart/YTVideoOverlay/assets/15531137/e34b8c92-fd8f-4fa8-a94f-44ca3af52053)

Crash logs:
https://pastebin.com/nPrNbzrJ

**Comment by PoomSmart** [comment]
@CySxL Rootful jailbreak?

**Comment by CySxL** [comment]
> @CySxL Rootful jailbreak?

Yes sir. iOS 14.8 on iPhone 11 Pro Max with unc0ver 8.0.2.

**Comment by PoomSmart** [comment]
@CySxL Can't seem to reproduce the bug. Anyway, here's a debug build of the tweak so I can see from which function it crashed at.

[com.ps.ytvideooverlay_1.1.1_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YTVideoOverlay/files/13255638/com.ps.ytvideooverlay_1.1.1_iphoneos-arm.deb.zip)

**Comment by CySxL** [comment]
> @CySxL Can't seem to reproduce the bug. Anyway, here's a debug build of the tweak so I can see from which function it crashed at.
> 
> 
> 
> [com.ps.ytvideooverlay_1.1.1_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YTVideoOverlay/files/13255638/com.ps.ytvideooverlay_1.1.1_iphoneos-arm.deb.zip)
> 
> 

Installed, how can I help with this build?

**Comment by PoomSmart** [comment]
@CySxL Just get the app to crash and produce the crash log.

**Comment by CySxL** [comment]
> @CySxL Just get the app to crash and produce the crash log.

Thanks! I've been testing it these days but seems the issue is gone now with both this test build and the repo build. So I guess it's Cr4shed blamed it wrongly on YTVideoOverlay while it's actually an old bug of YTLite. 

Because after the dev of YTLite fixed one of the bug about Shorts, Cr4shed hasn't reported any crashes from YTVideoOverlay for these days.

So I guess it's a false alarm, thank you so much for your time and the support!! Cheers!!
