### ISSUE TITLE
Doesn't work on latest YT build

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/YTVideoOverlay#8]
YouTube: 19.02.1

YTVideoOverly shows the preference in Settings but the buttons of YouMute and YouQuality are not displayed in video player.

Tester on iOS 14.8, rootful jailbreak (unc0ver)

**Comment by PoomSmart** [comment]
Fixed in v1.1.2

**Comment by CySxL** [comment]
> Fixed in v1.1.2

Confirmed fixed, thanks!
