### ISSUE TITLE
Overlay missing on older youtube verdion (16.45.4)

### ISSUE THREAD

**Issue by Landxhent** [PoomSmart/YTVideoOverlay#9]
On older youtube versio, overlay appears only when you drag the video progress bar. 

After you draggee video to the  required moment, and when the video player interface is automatically hidden - the overlay buttons disappear again. 

To make them reappear, it is needed to drag video progress bar again. Only like that.

On latest version everryghing works fine

**Comment by PoomSmart** [comment]
Can't seem to reproduce this issue on my iPad.

**Comment by PoomSmart** [comment]
Fixed in v1.1.6
